backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :characters do
    collection do 
      post 'acquire_characters'
    end
  end
  devise_scope :user do
	  authenticated :user do
	    root 'characters#index', as: :authenticated_root
	  end
		unauthenticated do
	   root "devise/sessions#new", as: :unauthenticated_root
	  end
  end
  ## API
  namespace :api , defaults: { format: 'json' } do
    namespace :v1 do
      resources :characters do 
        collection do 
          post 'update_characters'
        end
      end
    end
  end
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true
  validates_uniqueness_of :name
end

backend/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

backend/app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
  
end

backend/app/controllers/api/v1/characters_controller.rb
module Api
  module V1
    class CharactersController < V1Controller
      include ApplicationHelper

      def index
        
      end

      def show
        
      end

      def update_characters
        get_data_json('https://api.got.show/api/general/characters')
        render json: { status: :ok }
      end
      
      #def create
      #  @like = Like.new(like_params)
      #  if @like.save
      #    @status = :created
      #  else
      #    @status = :bad_request
      #  end
      #  render status: @status
      #end
      #
      #private
      #def like_params
      #  params.require(:like)
      #        .permit(:comment_id, :user_id)
      #end
    end
  end
end

backend/app/controllers/api/v1/v1_controller.rb
module Api
	class V1::V1Controller < ApiController
		before_action :check_api_key

    def check_api_key
      if request.headers['X-API-KEY'] != '836ed3a72c75b1e2b06ca755adefd382f5faf3a'
        return render json: { error: 'API Token inválido.' }, status: :bad_request
      end
    end

  end
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

backend/app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  include ApplicationHelper
  
  before_action :set_character, only: [:edit, :update,:show, :destroy]
  def index
    @characters = Character.all 
    respond_to do |format|
      format.html
      format.json { render json: CharactersDatatable.new(view_context, @characters) }
    end
  end

  def show 
  end

  def edit
  end
  
  def create
    @character = Character.new(character_params)
    respond_to do |format|
      if @character.save
        format.html { redirect_to characters_path }
      else
        format.html { render :new }
      end
    end
  end
  
  def new
    @character = Character.new
  end
  
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to character_path }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @character = @character.destroy 
    respond_to do |format|
      if @character.errors.present?
        puts ap @character.errors.messages
        format.html { redirect_to characters_url }
        format.json { head :no_content }
      else
        format.html { redirect_to characters_url}
        format.json { head :no_content }
      end
    end
  end
  
  def acquire_characters
    get_data_json('https://api.got.show/api/general/characters')
    respond_to do |format|
      format.html { redirect_to characters_path }
    end
  end

  private
  def set_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character)
          .permit(:name, :gender, :slug, :rank, :house)
  end

end

backend/app/helpers/application_helper.rb
module ApplicationHelper
 
  require 'uri'
  require 'net/http'
  require 'json'
    
  def get_data_json(url)
    url = url.gsub(" ","")
    escaped_address = URI.escape(url) 
    uri = URI.parse(url)

    if uri.kind_of?(URI::HTTP) or uri.kind_of?(URI::HTTPS)
      result = Net::HTTP.get_response(uri)
      if valid_json?(result.body)
        result = JSON.parse(result.body)
      else  
        return false  
      end
      if !result.nil? && !result['success'].nil? && result['success'] == 1 
        result['book'].each do |character|
          Character.create(name: character['name'], gender: character['gender'], slug: character['slug'],
           rank: character['pagerank']['rank'], house: character['house'])
        end
      end
    end
  end

  def valid_json?(string)
    begin
      !!JSON.parse(string)
    rescue JSON::ParserError
      false
    end
  end
end

backend/app/views/characters/_form.html.erb
<div class="form-group">
  <label class="col-sm-4 control-label">Name</label>
  <div class="col-sm-8">
  <%= f.input :name, input_html: { class: 'form-control' }, label: false , required: true%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">slug</label>
  <div class="col-sm-8">
  <%= f.input :slug, input_html: { class: 'form-control' }, label: false , required: false%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">Gender</label>
  <div class="col-sm-8">
    <%= select_tag 'gender', options_for_select( ['Male', 'Female'] ), label: false, required: false %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">rank</label>
  <div class="col-sm-8">
  <%= f.input :rank, input_html: { class: 'form-control' }, label: false , required: false%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">house</label>
  <div class="col-sm-8">
  <%= f.input :house, input_html: { class: 'form-control' }, label: false , required: false%>
  </div>
</div>
<div class="form-actions">
  <%= f.button :submit, class: "btn btn-success btn-sm" %>
  <%= link_to 'Back', characters_path, class: "btn btn-primary btn-sm" %>
</div>

backend/app/views/characters/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit character</h1>
    <%= simple_form_for([@character], wrapper: false, label: false, :method => :PATCH ) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

backend/app/views/characters/index.html.erb
<div class="row">
  <h1>All characters</h1>
</div>
<%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-danger pull-left" %>
<%= link_to 'Create Character', new_character_path ,class: "btn btn-success pull-left" %>
<%= link_to 'Get All Characters', acquire_characters_characters_path ,class: "btn btn-info pull-left", method: :post %>



<table class="table table-title" id="characters_datatable" data-source="<%= characters_path(format: "json") %>">
    <thead>
      <tr>
        <th>Name</th>
        <th>Gender</th>
        <th>Slug</th>
        <th>Rank</th>
        <th>House</th>
        <th>Created at</th>
        <th style="width: 300px;"></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
</table>

backend/app/views/characters/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New character</h1>
    <%= simple_form_for([@character], wrapper: false, label: false) do |f| %>
      <%= render 'form' , f: f %>
    <% end %>
  </div>
</div>

backend/app/views/characters/show.html.erb
<div class="form-group">
  <label class="col-sm-4 control-label">Name</label>
  <div class="col-sm-8">
  <%= @character.name%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">gender</label>
  <div class="col-sm-8">
  <%= @character.gender%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">slug</label>
  <div class="col-sm-8">
  <%= @character.slug %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">rank</label>
  <div class="col-sm-8">
  <%= @character.rank %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">house</label>
  <div class="col-sm-8">
  <%= @character.house %>
  </div>
</div>

<div class="form-group">
  <label class="col-sm-4 control-label">created_at date</label>
  <%= !@character.created_at.nil? ? @character.created_at.strftime("%d-%m-%y") : 'Doesnt have' %>
</div>

backend/app/views/layouts/_sidenav.html.erb
<div id="mySidenav" class="sidenav">
  <%= link_to 'Characters',characters_path %>
</div>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tachtech</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main">
      <% if !current_user.nil? %>
        <%= render "layouts/sidenav" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>